### ISSUE TITLE
Strict folding

### ISSUE THREAD

**Issue by ThibautVerron** [mattfidler/fold-dwim-org#1]
Hello,

Would it be possible/easy to implement an option for stricter folding, for example like it is done in org-mode (only fold if the point is on the folding mark)? Tab is a key we can use for a lot of purposes, simultaneously thanks to emacs' awesomeness, but having "fold at point" as the fallback behavior if nothing else is possible can be a pain.

**Comment by mattfidler** [comment]
Yes, it is possible.  I agree it is more desirable.  I have turned it on by default.  Let me know if it works for you.

**Comment by ThibautVerron** [comment]
Wow, that was fast!

Your patch indeed changed something, but it's not fully working : it looks like it won't fold when the point is on an indented line, but non-indented (and non-indentable) lines still trigger the fold.

Looking at the code, it looks like it only handles hideshow.el folds. I'm mostly using folding.el, so that may explain why it's not working for me. folding.el has a similar function as hs-find-block-beginning, named folding-find-folding-mark, but I have no idea how they should behave when one uses the two modes in a buffer. Checking for the loaded modes should be enough for most cases though.
I don't know how it could be extended to other modes supported by fold-dwim, either (most notably tex-fold).

From your code, I managed to get more or less the behavior I expected, by replacing fold-dwim-org/should-fold with the following code (sorry for the poor indentation, I don't have emacs on the computer I'm using to write this) : 

```
(defun fold-dwim-org/should-fold (last-point current-point)
  "* Checks to see if buffer has changed.  If not folding should occur. Then checks if we want strict folding, and if yes, if we are at a folding mark."
  (and (equal last-point current-point)
       (or (not fold-dwim-org-strict)
       (and fold-dwim-org-strict
        (or (and hs-minor-mode
             (= (point)
                (save-excursion
                  (hs-find-block-beginning)
                  (point))))
            (and (boundp 'folding-mode)
             folding-mode
             (= (line-number-at-pos (point))
                (line-number-at-pos (or (folding-find-folding-mark) (point))))))))) 
```

This also replaces the when condition you added in the first place (for selfish purpose, as it made the debugging easier), I'm not sure if it may cause unwanted side-effects. Anyway, that's just a sketch of course, and I definitely don't know what the proper test would be for all the modes supported by fold-dwim. 

All in all, I'm just posting it here in case it helps you.

**Comment by mattfidler** [comment]
I added this to the code, and need to think about how to hande LaTex.

**Comment by ThibautVerron** [comment]
Thank you!

As a short-term workaround, maybe it would be preferrable to test for other folding modes in the 'or' following the test for fold-dwim-org-strict. (The skipped question here is "is it better to fold non-strictly or to not fold at all?" But given that you made "strict" the default, users who update (and were potentially satisfied with the previous behavior) will suddenly have a non-working fold-dwim-org mode.)

The relevant variables are : 
- TeX-fold-mode (provided at mode load, so it has to be checked with boundp too)
- outline-minor-mode

fold-dwim also supports nXML-mode, but it looks like there is no nxml-mode variable defined. Instead, you can test (eq major-mode 'nxml-mode), but that's pretty dirty.

**Comment by mattfidler** [comment]
Thanks,

I think I will also need to add folding for end of hide-show marks too?
