### ISSUE TITLE
Update to 26.1

### ISSUE THREAD

**Issue by treymerkley** [mattfidler/fold-dwim-org#7]
Hi there! It looks like this package hasn't been updated in a while, and it doesn't work on modern Emacs, but I'd really like to use it; right now I'm just using TAB bound to dwim-toggle-fold. 

Is there any way you could take a look at it and get it limping on 26.1?

**Comment by mattfidler** [comment]
I have stopped using `org-mode` as much.  I think the new org-mode changed its engine so it would take me more time than I have to get it working with the new internals.

**Comment by treymerkley** [comment]
That's fair. Thanks for letting me know!

**Comment by mattfidler** [comment]
No problem.
